name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * 1"   # Runs every Monday
  workflow_dispatch:     # Allows manual run
permissions:
  contents: write
jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
          user: Theoslyy
          template: classic
          filename: github-metrics.svg
          config_timezone: America/Fortaleza
        
          # Base sections
          base: activity
        
          # Enable plugins
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_isocalendar: yes
          plugin_stars: yes

          plugin_languages_details: percentage
          
          repositories: 100
          repositories_affiliations: owner
