name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * 1"   # Runs every Monday
  workflow_dispatch:     # Allows manual run
permissions:
  contents: write
jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
          user: Theoslyy
          template: classic
          filename: github-metrics.svg
          config_timezone: America/Fortaleza
        
          # Base sections
          base: header, activity, repositories
        
          # Enable plugins
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_stars: yes
        
          # Languages plugin config
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 6
        
          # Isocalendar plugin config
          plugin_isocalendar_duration: half-year
        
          repositories_affiliations: owner
